### ISSUE TITLE
startup error

### ISSUE THREAD

**Issue by enchilada404** [interactive-sonification/sc3nb#15]
Hello,

I'm on Windows 10 64 bit, Python 3.9.2. I installed sc3nb with "pip install git+git://github.com/interactive-sonification/sc3nb@master" with no problems.

It imports fine, but fails during startup:

```
C:\Windows\System32>py
Python 3.9.2 (tags/v3.9.2:1a79785, Feb 19 2021, 13:44:55) [MSC v.1928 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import sc3nb as scn
>>> sc = scn.startup()
[sclang | start reading ]
[sclang]  compiling class library...
[sclang]        Found 853 primitives.
[sclang]        Compiling directory 'C:\Program Files\SuperCollider-3.12.0\SCClassLibrary'
[sclang]        Compiling directory 'C:\ProgramData\SuperCollider\Extensions'
[sclang]        Compiling directory 'C:\Users\falkd\AppData\Local\SuperCollider\Extensions'
[sclang]        Compiling directory 'E:/kodes/BEASTmulchLib/UGens/Loris'
[sclang]        Compiling directory 'C:\Users\falkd\AppData\Local\SuperCollider\downloaded-quarks\Debug'
[sclang]        numentries = 841243 / 12338370 = 0.068
[sclang]        5445 method selectors, 2266 classes
[sclang]        method table size 13478800 bytes, big table size 98706960
[sclang]        Number of Symbols 12244
[sclang]        Byte Code Size 370365
[sclang]        compiled 335 files in 1.87 seconds
[sclang]
[sclang]  Info: 2 methods are currently overwritten by extensions. To see which, execute:
[sclang]  MethodOverride.printAll
[sclang]
[sclang]  compile done
[sclang]  localhost : setting clientID to 0.
[sclang]  internal : setting clientID to 0.
[sclang]  Class tree inited in 0.04 seconds
[sclang]
[sclang]
[sclang]  *** Welcome to SuperCollider 3.12.0. *** For help press F1.
Starting sclang process... Done.
[sclang]  sc3nb - Registering OSC /return callback
[sclang]  -> ( 'callback': a Function )
Registering OSC /return callback in sclang... Done.
[sclang]  sc3nb - Loading SynthDefs from ^synthdef_path
[sclang]  -> [ PathName(C:\Program Files\Python39\lib\site-packages\sc3nb\resources\synthdefs\pb-1ch.scsyndef), PathName(C:\Program Files\Python39\lib\site-packages\sc3nb\resources\synthdefs\pb-2ch.scsyndef), PathName(C:\Program Files\Python39\lib\site-packages\sc3nb\resources\synthdefs\record-1ch.scsyndef), PathName(C:\Program Files\Python39\lib\site-packages\sc3nb\resources\synthdefs\record-2ch.scsyndef), PathName(C:\Program Files\Python39\lib\site-packages\sc3nb\resources\synthdefs\s1.scsyndef), PathName(C:\Program F...etc...
Loading default sc3nb SynthDefs... Done.
[scsynth | start reading ]
[scsynth]
[scsynth]  Device options:
[scsynth]    - MME : Microsoft Sound Mapper - Input   (device #0 with 2 ins 0 outs)
[scsynth]    - MME : Microphone (Intel SST Audio Dev   (device #1 with 2 ins 0 outs)
[scsynth]    - MME : Microsoft Sound Mapper - Output   (device #2 with 0 ins 2 outs)
[scsynth]    - MME : Speakers/Headphones (Intel SST    (device #3 with 0 ins 2 outs)
[scsynth]    - MME : SMT27A550 (Intel SST Audio Devi   (device #4 with 0 ins 2 outs)
[scsynth]    - Windows DirectSound : Primary Sound Capture Driver   (device #5 with 2 ins 0 outs)
[scsynth]    - Windows DirectSound : Microphone (Intel SST Audio Device (WDM))   (device #6 with 2 ins 0 outs)
[scsynth]    - Windows DirectSound : Primary Sound Driver   (device #7 with 0 ins 2 outs)
[scsynth]    - Windows DirectSound : Speakers/Headphones (Intel SST Audio Device (WDM))   (device #8 with 0 ins 2 outs)
[scsynth]    - Windows DirectSound : SMT27A550 (Intel SST Audio Device (WDM))   (device #9 with 0 ins 2 outs)
[scsynth]    - ASIO : ReaRoute ASIO (x64)   (device #10 with 16 ins 16 outs)
[scsynth]    - Windows WASAPI : Speakers/Headphones (Intel SST Audio Device (WDM))   (device #11 with 0 ins 2 outs)
[scsynth]    - Windows WASAPI : SMT27A550 (Intel SST Audio Device (WDM))   (device #12 with 0 ins 2 outs)
[scsynth]    - Windows WASAPI : Microphone (Intel SST Audio Device (WDM))   (device #13 with 2 ins 0 outs)
[scsynth]    - Windows WDM-KS : Output (IntelSST Audio Wave for Hdmi)   (device #14 with 0 ins 2 outs)
[scsynth]    - Windows WDM-KS : Speakers (IntelSST Audio Wave for IHF)   (device #15 with 0 ins 2 outs)
[scsynth]    - Windows WDM-KS : Microphone (IntelSST Audio Wave for DMIC)   (device #16 with 2 ins 0 outs)
[scsynth]
[scsynth]  Requested devices:
[scsynth]    In:
[scsynth]    - (default)
[scsynth]    Out:
[scsynth]    - (default)
[scsynth]
[scsynth]  Selecting default system input/output devices
[scsynth]
[scsynth]  Booting with:
[scsynth]    In: MME : Microphone (Intel SST Audio Dev
[scsynth]    Out: MME : Speakers/Headphones (Intel SST
[scsynth]    Sample rate: 44100.000
[scsynth]    Latency (in/out): 0.013 / 0.091 sec
[scsynth]  SC_AudioDriver: sample rate = 44100.000000, driver's block size = 64
[scsynth]  SuperCollider 3 server ready.
Booting SuperCollider Server... Done.
[sclang]  sc3nb - Connecting sclang to scsynth
[sclang]  sc3nb_remote : setting clientID to 0.
[sclang]  ERROR: Message 'protocol' not understood.
[sclang]  RECEIVER:
[sclang]     nil
[sclang]  ARGS:
[sclang]  CALL STACK:
[sclang]        DoesNotUnderstandError:reportError
[sclang]                arg this = <instance of DoesNotUnderstandError>
[sclang]        Nil:handleError
[sclang]                arg this = nil
[sclang]                arg error = <instance of DoesNotUnderstandError>
[sclang]        Thread:handleError
[sclang]                arg this = <instance of Thread>
[sclang]                arg error = <instance of DoesNotUnderstandError>
[sclang]        Object:throw
[sclang]                arg this = <instance of DoesNotUnderstandError>
[sclang]        Object:doesNotUnderstand
[sclang]                arg this = nil
[sclang]                arg selector = 'protocol'
[sclang]                arg args = [*0]
[sclang]        Meta_Server:remote
[sclang]                arg this = <instance of Meta_Server>
[sclang]                arg name = 'sc3nb_remote'
[sclang]                arg addr = <instance of NetAddr>
[sclang]                arg options = nil
[sclang]                arg clientID = 0
[sclang]                var result = <instance of Server>
[sclang]        < closed FunctionDef >  (no arguments or variables)
[sclang]        Interpreter:interpretPrintCmdLine
[sclang]                arg this = <instance of Interpreter>
[sclang]                var res = nil
[sclang]                var func = <instance of Function>
[sclang]                var code = ""sc3nb - Connecting sclang t..."
[sclang]                var doc = nil
[sclang]                var ideClass = nil
[sclang]        Process:interpretPrintCmdLine
[sclang]                arg this = <instance of Main>
[sclang]  ^^ ERROR: Message 'protocol' not understood.
[sclang]  RECEIVER: nil
[sclang]
[sclang]
Timeout while reading sclang
expected: "->" (sclang return value)
output until timeout below: (also see console)
----------------------------------------------
sc3nb - Connecting sclang to scsynth
sc3nb_remote : setting clientID to 0.
ERROR: Message 'protocol' not understood.
RECEIVER:
   nil
ARGS:
CALL STACK:
        DoesNotUnderstandError:reportError
                arg this = <instance of DoesNotUnderstandError>
        Nil:handleError
                arg this = nil
                arg error = <instance of DoesNotUnderstandError>
        Thread:handleError
                arg this = <instance of Thread>
                arg error = <instance of DoesNotUnderstandError>
        Object:throw
                arg this = <instance of DoesNotUnderstandError>
        Object:doesNotUnderstand
                arg this = nil
                arg selector = 'protocol'
                arg args = [*0]
        Meta_Server:remote
                arg this = <instance of Meta_Server>
                arg name = 'sc3nb_remote'
                arg addr = <instance of NetAddr>
                arg options = nil
                arg clientID = 0
                var result = <instance of Server>
        < closed FunctionDef >  (no arguments or variables)
        Interpreter:interpretPrintCmdLine
                arg this = <instance of Interpreter>
                var res = nil
                var func = <instance of Function>
                var code = ""sc3nb - Connecting sclang t..."
                var doc = nil
                var ideClass = nil
        Process:interpretPrintCmdLine
                arg this = <instance of Main>
^^ ERROR: Message 'protocol' not understood.
RECEIVER: nil



Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\site-packages\sc3nb\sc.py", line 280, in _try_to_connect
    self._sclang.connect_to_server(self._server)
  File "C:\Program Files\Python39\lib\site-packages\sc3nb\sclang.py", line 456, in connect_to_server
    self.cmds(code.format(*server.addr, SC3NB_SCLANG_CLIENT_ID))
  File "C:\Program Files\Python39\lib\site-packages\sc3nb\sclang.py", line 337, in cmds
    return self.cmd(code, verbose=False, **kwargs)
  File "C:\Program Files\Python39\lib\site-packages\sc3nb\sclang.py", line 318, in cmd
    out = self.read(expect=self._repl_return, timeout=timeout)
  File "C:\Program Files\Python39\lib\site-packages\sc3nb\sclang.py", line 383, in read
    raise timeout_error
  File "C:\Program Files\Python39\lib\site-packages\sc3nb\sclang.py", line 370, in read
    return self.process.read(expect=expect, timeout=timeout)
  File "C:\Program Files\Python39\lib\site-packages\sc3nb\process_handling.py", line 245, in read
    raise ProcessTimeout(
sc3nb.process_handling.ProcessTimeout: Reading of sclang timed out after 1s while expecting: "->"

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files\Python39\lib\site-packages\sc3nb\sc.py", line 67, in startup
    SC.default = SC(
  File "C:\Program Files\Python39\lib\site-packages\sc3nb\sc.py", line 177, in __init__
    self.start_server(
  File "C:\Program Files\Python39\lib\site-packages\sc3nb\sc.py", line 271, in start_server
    self._try_to_connect()
  File "C:\Program Files\Python39\lib\site-packages\sc3nb\sc.py", line 282, in _try_to_connect
    raise RuntimeError(
RuntimeError: connecting <SCLang process=<Process 'sclang' (running) pid=11764>> to <SCServer addr=('127.0.0.1', 57110), process=<Process 'scsynth' (running) pid=7052>> failed
```

Any ideas?

**Comment by dreinsch** [comment]
Hi,

thank you very much for reporting this issue and using sc3nb!

It seems like this problem occurs with the 3.12 version of SuperCollider on Windows.
This happens when we try to connect the sclang and scsynth instance.
I will try to find out what is causing the error.

In the meanwhile there are 2 workarounds:

- If you still have 3.11 installed you could try using it for now with
   `sc = scn.startup(sclang_path="C:\Program Files\SuperCollider-3.11.0")`
- You could use scsynth only by using
  `sc = scn.startup(start_sclang=False)`
  However then some features of sc3nb will not work

**Comment by dreinsch** [comment]
@enchilada404 Can you try to install the develop branch? I just pushed a workaround to fix this issue.

**Comment by enchilada404** [comment]
Yes!

Confirmed working here after installing the new develop branch.

```
C:\Windows\System32>py
Python 3.9.2 (tags/v3.9.2:1a79785, Feb 19 2021, 13:44:55) [MSC v.1928 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import sc3nb as scn
>>> sc = scn.startup()
[sclang | start reading ]
[sclang]  compiling class library...
[sclang]        Found 853 primitives.
[sclang]        Compiling directory 'C:\Program Files\SuperCollider-3.12.0\SCClassLibrary'
[sclang]        Compiling directory 'C:\ProgramData\SuperCollider\Extensions'
[sclang]        Compiling directory 'C:\Users\falkd\AppData\Local\SuperCollider\Extensions'
[sclang]        Compiling directory 'E:/kodes/BEASTmulchLib/UGens/Loris'
[sclang]        Compiling directory 'C:\Users\falkd\AppData\Local\SuperCollider\downloaded-quarks\Debug'
[sclang]        numentries = 841243 / 12338370 = 0.068
[sclang]        5445 method selectors, 2266 classes
[sclang]        method table size 13478800 bytes, big table size 98706960
[sclang]        Number of Symbols 12244
[sclang]        Byte Code Size 370365
[sclang]        compiled 335 files in 4.03 seconds
[sclang]
[sclang]  Info: 2 methods are currently overwritten by extensions. To see which, execute:
[sclang]  MethodOverride.printAll
[sclang]
[sclang]  compile done
[sclang]  localhost : setting clientID to 0.
[sclang]  internal : setting clientID to 0.
[sclang]  Class tree inited in 0.05 seconds
[sclang]
[sclang]
[sclang]  *** Welcome to SuperCollider 3.12.0. *** For help press F1.
Starting sclang process... Done.
[sclang]  sc3nb - Registering OSC /return callback
[sclang]  -> ( 'callback': a Function )
Registering OSC /return callback in sclang... Done.
[sclang]  sc3nb - Loading SynthDefs from ^synthdef_path
[sclang]  -> [ PathName(C:\Users\falkd\AppData\Roaming\Python\Python39\site-packages\sc3nb\resources\synthdefs\pb-1ch.scsyndef), PathName(C:\Users\falkd\AppData\Roaming\Python\Python39\site-packages\sc3nb\resources\synthdefs\pb-2ch.scsyndef), PathName(C:\Users\falkd\AppData\Roaming\Python\Python39\site-packages\sc3nb\resources\synthdefs\record-1ch.scsyndef), PathName(C:\Users\falkd\AppData\Roaming\Python\Python39\site-packages\sc3nb\resources\synthdefs\record-2ch.scsyndef), PathName(C:\Users\falkd\AppData\Roaming\Python...etc...
Loading default sc3nb SynthDefs... Done.
[scsynth | start reading ]
[scsynth]
[scsynth]  Device options:
[scsynth]    - MME : Microsoft Sound Mapper - Input   (device #0 with 2 ins 0 outs)
[scsynth]    - MME : Microphone (Intel SST Audio Dev   (device #1 with 2 ins 0 outs)
[scsynth]    - MME : Microsoft Sound Mapper - Output   (device #2 with 0 ins 2 outs)
[scsynth]    - MME : Speakers/Headphones (Intel SST    (device #3 with 0 ins 2 outs)
[scsynth]    - MME : SMT27A550 (Intel SST Audio Devi   (device #4 with 0 ins 2 outs)
[scsynth]    - Windows DirectSound : Primary Sound Capture Driver   (device #5 with 2 ins 0 outs)
[scsynth]    - Windows DirectSound : Microphone (Intel SST Audio Device (WDM))   (device #6 with 2 ins 0 outs)
[scsynth]    - Windows DirectSound : Primary Sound Driver   (device #7 with 0 ins 2 outs)
[scsynth]    - Windows DirectSound : Speakers/Headphones (Intel SST Audio Device (WDM))   (device #8 with 0 ins 2 outs)
[scsynth]    - Windows DirectSound : SMT27A550 (Intel SST Audio Device (WDM))   (device #9 with 0 ins 2 outs)
[scsynth]    - ASIO : ReaRoute ASIO (x64)   (device #10 with 16 ins 16 outs)
[scsynth]    - Windows WASAPI : Speakers/Headphones (Intel SST Audio Device (WDM))   (device #11 with 0 ins 2 outs)
[scsynth]    - Windows WASAPI : SMT27A550 (Intel SST Audio Device (WDM))   (device #12 with 0 ins 2 outs)
[scsynth]    - Windows WASAPI : Microphone (Intel SST Audio Device (WDM))   (device #13 with 2 ins 0 outs)
[scsynth]    - Windows WDM-KS : Output (IntelSST Audio Wave for Hdmi)   (device #14 with 0 ins 2 outs)
[scsynth]    - Windows WDM-KS : Speakers (IntelSST Audio Wave for IHF)   (device #15 with 0 ins 2 outs)
[scsynth]    - Windows WDM-KS : Microphone (IntelSST Audio Wave for DMIC)   (device #16 with 2 ins 0 outs)
[scsynth]
[scsynth]  Requested devices:
[scsynth]    In:
[scsynth]    - (default)
[scsynth]    Out:
[scsynth]    - (default)
[scsynth]
[scsynth]  Selecting default system input/output devices
[scsynth]
[scsynth]  Booting with:
[scsynth]    In: MME : Microphone (Intel SST Audio Dev
[scsynth]    Out: MME : Speakers/Headphones (Intel SST
[scsynth]    Sample rate: 44100.000
[scsynth]    Latency (in/out): 0.013 / 0.091 sec
[scsynth]  SC_AudioDriver: sample rate = 44100.000000, driver's block size = 64
[scsynth]  SuperCollider 3 server ready.
Booting SuperCollider Server... Done.
[sclang]  sc3nb - Connecting sclang to scsynth
[sclang]  sc3nb_remote : setting clientID to 0.
[sclang]  -> Server
[sclang]  -> 57120
[sclang]  sc3nb - Creating SynthDef sc3nb_volumeAmpControl2
[sclang]  -> Int8Array[ 83, 67, 103, 102, 0, 0, 0, 2, 0, 1, 23, 115, 99, 51, 110, 98, 95, 118, 111, 108, 117, 109, 101, 65, 109, 112, 67, 111, 110, 116, 114, 111, 108, 50, 0, 0, 0, 4, 60, 35, -41, 10, 63, -128, 0, 0, 61, 76, -52, -51, 64, 0, 0, 0, 0, 0, 0, 4, 63, -128, 0, 0, 61, -52, -52, -51, 63, -128, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 9, 118, 111, 108, 117, 109, 101, 65, 109, 112, 0, 0, 0, 0, 9, 118, 111, 108, 117, 109, 101, 76, 97, 103, 0, 0, 0, 1, 4, 103, 97, 116, 101, 0, 0, 0, 2, 3, 98, 117, 115, 0, 0, 0, 3, 0, 0, 0, 7...etc...
>>> [sclang]  Requested notification messages from server 'sc3nb_remote'
[sclang]  sc3nb_remote: server process has maxLogins 8 - adjusting my options accordingly.
[sclang]  sc3nb_remote: keeping clientID (0) as confirmed by server process.

>>> sc.server.blip()
>>> sc.server.status()
ServerStatus(num_ugens=0, num_synths=0, num_groups=9, num_synthdefs=115, avg_cpu=0.3841515779495239, peak_cpu=0.5595266222953796, nominal_sr=44100.0, actual_sr=44107.04173512981)
>>> sc.server.dump_tree()
[scsynth]  NODE TREE Group 0
[scsynth]     469762049 group
[scsynth]     402653185 group
[scsynth]     335544321 group
[scsynth]     268435457 group
[scsynth]     201326593 group
[scsynth]     134217729 group
[scsynth]     67108865 group
[scsynth]     1 group
NODE TREE Group 0
   469762049 group
   402653185 group
   335544321 group
   268435457 group
   201326593 group
   134217729 group
   67108865 group
   1 group
```

Thanks for taking your time to fix this, and also for creating sc3nb in the first place, it's looking really promising.

👍

**Comment by dreinsch** [comment]
Thank you very much for checking it out!
If you run into other problems or have suggestions feel free to open another issue or get in touch.
