### ISSUE TITLE
crashing on start-up

### ISSUE THREAD

**Issue by n-otter** [interactive-sonification/sc3nb#19]
Hello,

I installed sc3nb with pip and python 3.10.8. When running

```
import sc3nb as scn
sc = scn.startup()
```

I get the error message below:

``` >>> sc = scn.startup()

[sclang | start reading ]
[sclang]  compiling class library...
[sclang]  	Found 855 primitives.
[sclang]  	Compiling directory '/Applications/SuperCollider.app/Contents/Resources/SCClassLibrary'
[sclang]  	Compiling directory '/Users/User/Library/Application Support/SuperCollider/Extensions'
[sclang]  	numentries = 838063 / 12430290 = 0.067
[sclang]  	5505 method selectors, 2258 classes
[sclang]  	method table size 13367560 bytes, big table size 99442320
[sclang]  	Number of Symbols 12375
[sclang]  	Byte Code Size 378538
[sclang]  	compiled 328 files in 0.60 seconds
[sclang]  compile done
[sclang]  localhost : setting clientID to 0.
[sclang]  internal : setting clientID to 0.
[sclang]  Class tree inited in 0.01 seconds
[sclang]  
[sclang]  
[sclang]  *** Welcome to SuperCollider 3.13.0. *** For help type cmd-d.
Starting sclang process... Done.
[sclang]  sc3> "sc3nb - Registering OSC /return callback".postln; r = r ? (); r.callback = { arg code, ip, port; var result = code.interpret; var addr = NetAddr.new(ip, port); var prependSize = { arg elem; if (elem.class == Array){ elem = [elem.size] ++ elem.collect(prependSize); }{ elem; }; }; var msgContent = prependSize.value(result); addr.sendMsg("/return", msgContent); result; };
[sclang]  sc3nb - Registering OSC /return callback
[sclang]  -> ( 'callback': a Function )
Registering OSC /return callback in sclang... Done.
[sclang]  sc3> "sc3nb - Loading SynthDefs from ^synthdef_path".postln; PathName.new("/Users/User/miniconda3/lib/python3.10/site-packages/sc3nb/resources/synthdefs").files.collect( { |path| (path.extension == "scsyndef").if({SynthDescLib.global.read(path); path;})} );
[sclang]  sc3nb - Loading SynthDefs from ^synthdef_path
[sclang]  -> [ nil, PathName(/Users/User/miniconda3/lib/python3.10/site-packages/sc3nb/resources/synthdefs/pb-1ch.scsyndef), PathName(/Users/User/miniconda3/lib/python3.10/site-packages/sc3nb/resources/synthdefs/pb-2ch.scsyndef), PathName(/Users/User/miniconda3/lib/python3.10/site-packages/sc3nb/resources/synthdefs/record-1ch.scsyndef), PathName(/Users/User/miniconda3/lib/python3.10/site-packages/sc3nb/resources/synthdefs/record-2ch.scsyndef), PathName(/Users/User/miniconda3/lib/python3.10/site-packages/sc3nb/resources/...etc...
Loading default sc3nb SynthDefs... Done.
[scsynth | start reading ]
[scsynth]  Number of Devices: 2
[scsynth]     0 : "MacBook Air Microphone"
[scsynth]     1 : "MacBook Air Speakers"
[scsynth]  
[scsynth]  ERROR: Input sample rate is 48000, but output is 44100. Mismatched sample rates are not supported. To disable input, set the number of input channels to 0.
[scsynth]  could not initialize audio.
[scsynth]  libc++abi: terminating
[scsynth | reached EOF ]


Booting SuperCollider Server... Failed booting SuperCollider Server.
Traceback (most recent call last):
  File "/Users/User/miniconda3/lib/python3.10/site-packages/sc3nb/sc.py", line 260, in start_server
    self._server.boot(
  File "/Users/User/miniconda3/lib/python3.10/site-packages/sc3nb/sc_objects/server.py", line 438, in boot
    raise process_timeout
  File "/Users/User/miniconda3/lib/python3.10/site-packages/sc3nb/sc_objects/server.py", line 416, in boot
    self.process.read(
  File "/Users/User/miniconda3/lib/python3.10/site-packages/sc3nb/process_handling.py", line 247, in read
    raise ProcessTimeout(
sc3nb.process_handling.ProcessTimeout: Reading of scsynth timed out after 10s while expecting: "SuperCollider 3 server ready."

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/User/miniconda3/lib/python3.10/site-packages/sc3nb/sc.py", line 67, in startup
    SC.default = SC(
  File "/Users/User/miniconda3/lib/python3.10/site-packages/sc3nb/sc.py", line 177, in __init__
    self.start_server(
  File "/Users/User/miniconda3/lib/python3.10/site-packages/sc3nb/sc.py", line 269, in start_server
    raise RuntimeError(f"Starting scsynth failed - {excep}") from excep
RuntimeError: Starting scsynth failed - Reading of scsynth timed out after 10s while expecting: "SuperCollider 3 server ready."
```

Using the solution provided in the previous issue doesn't help either, as I get the error message:

```
>>> sc.start_server()

[scsynth | start reading ]
[scsynth]  Number of Devices: 2
[scsynth]     0 : "MacBook Air Microphone"
[scsynth]     1 : "MacBook Air Speakers"
[scsynth]  
[scsynth]  ERROR: Input sample rate is 48000, but output is 44100. Mismatched sample rates are not supported. To disable input, set the number of input channels to 0.
[scsynth]  could not initialize audio.
[scsynth]  libc++abi: terminating
[scsynth | reached EOF ]
Booting SuperCollider Server... Failed booting SuperCollider Server.
Traceback (most recent call last):
  File "/Users/User/miniconda3/lib/python3.10/site-packages/sc3nb/sc.py", line 260, in start_server
    self._server.boot(
  File "/Users/User/miniconda3/lib/python3.10/site-packages/sc3nb/sc_objects/server.py", line 438, in boot
    raise process_timeout
  File "/Users/User/miniconda3/lib/python3.10/site-packages/sc3nb/sc_objects/server.py", line 416, in boot
    self.process.read(
  File "/Users/User/miniconda3/lib/python3.10/site-packages/sc3nb/process_handling.py", line 247, in read
    raise ProcessTimeout(
sc3nb.process_handling.ProcessTimeout: Reading of scsynth timed out after 5s while expecting: "SuperCollider 3 server ready."

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/User/miniconda3/lib/python3.10/site-packages/sc3nb/sc.py", line 269, in start_server
    raise RuntimeError(f"Starting scsynth failed - {excep}") from excep
RuntimeError: Starting scsynth failed - Reading of scsynth timed out after 5s while expecting: "SuperCollider 3 server ready."
```

I am not sure if the issue is entirely due to the mismatch between input sample rate and output sample rate. I haven't been able to understand how to set the input channels to 0, as suggested in the error message. Could you please help me with this?

**Comment by dreinsch** [comment]
Hi,

you can specifiy the number of input channels using `ServerOptions`

```
import sc3nb as scn
sc = scn.startup(scsynth_options=scn.ServerOptions(num_input_buses=0))
```

But this will obviously won't allow you to use audio input.

If you want to use input you need to match the sampling rate of your input/output device in System Preferences > Audio/MIDI Setup.
More details can be found here:
- https://doc.sccode.org/Reference/AudioDeviceSelection.html
- https://scsynth.org/t/input-sampling-rate-does-not-match-the-output/562/3

**Comment by n-otter** [comment]
Thank you very much for your quick response! I managed to solve my issue by changing the sampling rate of the input/output on my laptop.
